/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BomberosVistas;

import BomberoAcceesoDatos.BomberoData;
import BomberoAcceesoDatos.BrigadaData;
import BomberoAcceesoDatos.CuartelData;
import BomberoAcceesoDatos.SiniestrosData;
import BomberosEntidades.Bombero;
import BomberosEntidades.Cuartel;
import BomberosEntidades.Especialidad;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import BomberosEntidades.Brigada;
import BomberosEntidades.Siniestro;

/**
 *
 * @author pollo
 */
public class FormularioBrigada extends javax.swing.JInternalFrame {

    private Brigada brigadaActual = null;

    private BomberoData bomberodata = new BomberoData();
    private Bombero bomberoActual = null;
    private FormularioBrigada brigada;
    CuartelData cd = new CuartelData();
    List<Cuartel> listaCuartel = cd.listaCuarteles();
    private BrigadaData bData = new BrigadaData();
    DefaultTableModel modelo = new DefaultTableModel();
    List<Bombero> listarBomberos = bomberodata.listaBomberos();
    private List<BomberosEntidades.Brigada> listaBrigadas = bData.listarBrigadasLibres();
    DefaultComboBoxModel comboModelo = new DefaultComboBoxModel(listaCuartel.toArray());
    DefaultTableModel modelo2 = new DefaultTableModel();
    private SiniestrosData sn = new SiniestrosData();
    List<Siniestro> listarSiniestro = sn.listarSiniestroSinBrigada();
    List<BomberosEntidades.Brigada> brigadas = bData.listarBrigadasLibres();
    List<Siniestro> listarSiniestroTodos = sn.listarSiniestros();
    List<BomberosEntidades.Brigada> Todasbrigadas = bData.listarBrigadasAsignadas();

    /**
     * Creates new form Brigada
     */
    public FormularioBrigada() {
        initComponents();
        armarTabla2();
        llenarTipo();
        ArmarTabla();
        llenarTablaSiniestro();
        llenarCuartel();
        llenarTabla();
        limpiarCampos();
    }

    private void ArmarTabla() {
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Especialidad");
        modelo.addColumn("Cuartel");
        jTBrigada.setModel(modelo);
    }

    //
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBrigada = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jCtipo = new javax.swing.JComboBox<>();
        jcCuartel = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTSiniestro = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jAsignar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFiltrar = new javax.swing.JButton();
        jEspecialidadFiltro = new javax.swing.JComboBox<>();
        jcCuartelFiltro = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        liompiarfasasdasd = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jModificar = new javax.swing.JButton();
        jAsignadaSiniestreo = new javax.swing.JRadioButton();
        jNoAsignadaSiniestro = new javax.swing.JRadioButton();
        jAsignadasBrigada = new javax.swing.JRadioButton();
        jNoasignadaBrigada = new javax.swing.JRadioButton();

        jLabel1.setText("Brigada");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Especialida:");

        jLabel4.setText("Cuartel: ");

        jTBrigada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTBrigada);

        jButton1.setText("Selecionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Nuevo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jCtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtipoActionPerformed(evt);
            }
        });

        jcCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCuartelActionPerformed(evt);
            }
        });

        jTSiniestro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTSiniestro);

        jLabel5.setText("Siniestros");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jAsignar.setText("Asignar");
        jAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAsignarActionPerformed(evt);
            }
        });

        jLabel6.setText("  ");

        jLabel7.setText("  ");

        jFiltrar.setText("Filtrar");
        jFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFiltrarActionPerformed(evt);
            }
        });

        jEspecialidadFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEspecialidadFiltroActionPerformed(evt);
            }
        });

        jLabel8.setText("FILTROS");

        jLabel9.setText("Cuartel: ");

        liompiarfasasdasd.setText("Limpiar");
        liompiarfasasdasd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liompiarfasasdasdActionPerformed(evt);
            }
        });

        jLabel10.setText("Especialida:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addGap(130, 130, 130)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(liompiarfasasdasd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcCuartelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jAsignar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFiltrar))
                            .addComponent(jEspecialidadFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel10)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jEspecialidadFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jcCuartelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAsignar)
                    .addComponent(jFiltrar)
                    .addComponent(liompiarfasasdasd))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jLabel10)
                    .addContainerGap(120, Short.MAX_VALUE)))
        );

        jModificar.setText("Modificar");
        jModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarActionPerformed(evt);
            }
        });

        jAsignadaSiniestreo.setText("Asignadas");
        jAsignadaSiniestreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAsignadaSiniestreoActionPerformed(evt);
            }
        });

        jNoAsignadaSiniestro.setText("No Asignadas");
        jNoAsignadaSiniestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoAsignadaSiniestroActionPerformed(evt);
            }
        });

        jAsignadasBrigada.setText("Asignadas");
        jAsignadasBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAsignadasBrigadaActionPerformed(evt);
            }
        });

        jNoasignadaBrigada.setText("No Asignadas");
        jNoasignadaBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoasignadaBrigadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jModificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jcCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(275, 275, 275)
                                        .addComponent(jAsignadaSiniestreo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jNoAsignadaSiniestro)
                                        .addGap(23, 23, 23))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(332, 332, 332)
                                            .addComponent(jButton5))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jAsignadasBrigada)
                                .addGap(31, 31, 31)
                                .addComponent(jNoasignadaBrigada)
                                .addGap(31, 31, 31))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jCtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jModificar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jAsignadasBrigada)
                                .addComponent(jNoasignadaBrigada)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAsignadaSiniestreo)
                            .addComponent(jNoAsignadaSiniestro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try {
            Cuartel cuartel;
            Brigada brigada;
            String nombre = jtNombre.getText();
            Especialidad esp = (Especialidad) jCtipo.getSelectedItem();
            cuartel = (Cuartel) jcCuartel.getSelectedItem();
            brigada = new Brigada(nombre, esp, cuartel);
            bData.agregarBrigada(brigada);
            
            limpiarCampos();
      
            JOptionPane.showMessageDialog(this, "La brigada '" + brigada + "' a sido guardada exitosamente.");

        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "No debe haber campos vacios ");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCtipoActionPerformed

    private void liompiarfasasdasdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liompiarfasasdasdActionPerformed
        // TODO add your handling code here:
        limpiarCampos();

    }//GEN-LAST:event_liompiarfasasdasdActionPerformed

    private void jAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAsignarActionPerformed

        // TODO add your handling code here:
        try {
            if (!jAsignadaSiniestreo.isSelected() && !jAsignadasBrigada.isSelected()) {

                int filaSeleccionada = jTSiniestro.getSelectedRow();
                int filaSeleccionada2 = jTBrigada.getSelectedRow();
                if (filaSeleccionada != -1 && filaSeleccionada2 != -1) {
                    Object codSiniestro = jTSiniestro.getValueAt(filaSeleccionada, 0);
                    Object codBrigada = jTBrigada.getValueAt(filaSeleccionada2, 0);
                    int CodS = Integer.parseInt(codSiniestro.toString());
                    int codB = Integer.parseInt(codBrigada.toString());
                    Brigada bd = bData.buscarBrigadaPorId(codB);
                    Siniestro siniestro = new Siniestro();

                    bData.asignarBrigadaSiniestro(bd.getCodBrigada());
                    siniestro.setCodigo(CodS);
                    sn.asignarBrigada(siniestro, bd);
                    limpiarTabla();
                } else {
                    JOptionPane.showMessageDialog(this, "Fila seleccionada invalida");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione la tabla de no asignados");

            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Los datos tomados del sistema son incorrectos ");
        }
    }//GEN-LAST:event_jAsignarActionPerformed

    private void jEspecialidadFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEspecialidadFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEspecialidadFiltroActionPerformed

    private void jcCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCuartelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcCuartelActionPerformed

    private void jFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFiltrarActionPerformed
        // TODO add your handling code here:

        modelo2.setRowCount(0);

        for (Siniestro aux : listarSiniestro) {
            if (aux.getTipoSiniestro().equals(jEspecialidadFiltro.getSelectedItem())) {
                String codigo = "No asignada";
                if (aux.getCodigoBrigada() != null) {
                    codigo = "" + aux.getCodigoBrigada().getCodBrigada() + "-" + aux.getCodigoBrigada().getNombreBrigada();
                }
                modelo2.addRow(new Object[]{aux.getCodigo(), aux.getFechaSiniestro(), aux.getTipoSiniestro(), codigo, aux.getDetalles()});
            }
        }
        modelo.setRowCount(0);
        for (Brigada aux : brigadas) {
            String nombre = "";
            for (Cuartel cuartel : listaCuartel) {
                if (cuartel.getCodCuartel() == aux.getNro_cuartel().getCodCuartel()) {
                    nombre = cuartel.getNombre();
                }
            }
            if (aux.getEspecialidad().equals(jEspecialidadFiltro.getSelectedItem())
                    && nombre.equalsIgnoreCase(jcCuartelFiltro.getSelectedItem().toString())) {
                modelo.addRow(new Object[]{aux.getCodBrigada(), aux.getNombreBrigada(), aux.getEspecialidad(), nombre});
            }
        }


    }//GEN-LAST:event_jFiltrarActionPerformed

    private void jModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jModificarActionPerformed

    private void jAsignadaSiniestreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAsignadaSiniestreoActionPerformed
        // TODO add your handling code here:
        if (jAsignadaSiniestreo.isSelected() == true) {
            jNoAsignadaSiniestro.setSelected(false);
        }
        modelo2.setRowCount(0);
        for (Siniestro aux : listarSiniestroTodos) {
            String codigo = "No asignada";
            if (aux.getCodigoBrigada() != null) {
                codigo = "" + aux.getCodigoBrigada().getCodBrigada() + "-" + aux.getCodigoBrigada().getNombreBrigada();
                modelo2.addRow(new Object[]{aux.getCodigo(), aux.getFechaSiniestro(), aux.getTipoSiniestro(), codigo, aux.getDetalles()});
            }
        }
    }//GEN-LAST:event_jAsignadaSiniestreoActionPerformed

    private void jAsignadasBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAsignadasBrigadaActionPerformed
        // TODO add your handling code here:
        if (jAsignadasBrigada.isSelected() == true) {
            jNoasignadaBrigada.setSelected(false);
        }
        modelo.setRowCount(0);
        for (Brigada aux : Todasbrigadas) {
            String nombre = "";
            for (Cuartel cuartel : listaCuartel) {
                if (cuartel.getCodCuartel() == aux.getNro_cuartel().getCodCuartel()) {
                    nombre = cuartel.getNombre();
                }
            }
            modelo.addRow(new Object[]{aux.getCodBrigada(), aux.getNombreBrigada(), aux.getEspecialidad(), nombre});
        }
    }//GEN-LAST:event_jAsignadasBrigadaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Salir
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jNoasignadaBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoasignadaBrigadaActionPerformed
        // TODO add your handling code here:
        if (jNoasignadaBrigada.isSelected() == true) {
            jAsignadasBrigada.setSelected(false);
        }
        llenarTabla();
    }//GEN-LAST:event_jNoasignadaBrigadaActionPerformed

    private void jNoAsignadaSiniestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoAsignadaSiniestroActionPerformed
        // TODO add your handling code here:
        if (jNoAsignadaSiniestro.isSelected() == true) {
            jAsignadaSiniestreo.setSelected(false);
        }
        llenarTablaSiniestro();
    }//GEN-LAST:event_jNoAsignadaSiniestroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTBrigada.getSelectedRow();
        if (filaSeleccionada != -1) {
            Object IdBrigada = jTBrigada.getValueAt(filaSeleccionada, 0);
            if (IdBrigada != null) {
                int numero = Integer.parseInt(IdBrigada.toString());
                brigadaActual = bData.buscarBrigadaPorId(numero);
                if (brigadaActual != null) {
                    jtNombre.setText(brigadaActual.getNombreBrigada());
                    jCtipo.setSelectedItem(brigadaActual.getEspecialidad());
                    System.out.println(brigadaActual.getNro_cuartel());
                    System.out.println(jcCuartel.getSelectedItem());
                    for (Cuartel cuartel : listaCuartel) {
                        if (cuartel.getCodCuartel() == brigadaActual.getNro_cuartel().getCodCuartel()) {
                            jcCuartel.setSelectedItem(cuartel);
                        }
                    }
//                        jDni.setText(bomberoActual.getDni());
//                        Jnombre.setText(bomberoActual.getNombre());
//                        JApellido.setText(bomberoActual.getApellido());
//                        jCelular.setText(bomberoActual.getCelular());
//                        jSangre.setSelectedItem(bomberoActual.getGrupSanguineo());
//                        jBrigadaAsignada.setSelectedItem(bomberoActual.getBrigada());
//                        jDCalendar.setDate(Date.from(bomberoActual.getFecha_nac().atStartOfDay(ZoneId.systemDefault()).toInstant()));
                } else {
                    JOptionPane.showMessageDialog(this, "Bombero no encontrado");
                }
            } else {
                JOptionPane.showMessageDialog(this, "El valor seleccionado es nulo");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna fila");
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    private void limpiarTabla() {
        int filas = modelo.getRowCount();
        for (int i = filas - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    private void limpiarCampos() {
        limpiarTabla();
        llenarTabla();
        llenarTablaSiniestro();
        jAsignadaSiniestreo.setSelected(false);
        jAsignadasBrigada.setSelected(false);
        jNoAsignadaSiniestro.setSelected(true);
        jNoasignadaBrigada.setSelected(true);
        jtNombre.setText("");
        jCtipo.setSelectedIndex(0);
        jcCuartel.setSelectedIndex(0);
        jTBrigada.clearSelection();
        jTSiniestro.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jAsignadaSiniestreo;
    private javax.swing.JRadioButton jAsignadasBrigada;
    private javax.swing.JButton jAsignar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<Especialidad> jCtipo;
    private javax.swing.JComboBox<Especialidad> jEspecialidadFiltro;
    private javax.swing.JButton jFiltrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jModificar;
    private javax.swing.JRadioButton jNoAsignadaSiniestro;
    private javax.swing.JRadioButton jNoasignadaBrigada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTBrigada;
    private javax.swing.JTable jTSiniestro;
    private javax.swing.JComboBox<Cuartel> jcCuartel;
    private javax.swing.JComboBox<Cuartel> jcCuartelFiltro;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JButton liompiarfasasdasd;
    // End of variables declaration//GEN-END:variables
public void llenarTipo() {
        for (Especialidad tipo : Especialidad.values()) {
            jCtipo.addItem(tipo);
            jEspecialidadFiltro.addItem(tipo);
        }
    }

    public void llenarTablaSiniestro() {
        modelo2.setRowCount(0);
        listarSiniestro=sn.listarSiniestroSinBrigada();
        for (Siniestro aux : listarSiniestro) {
            String codigo = "No asignada";
            if (aux.getCodigoBrigada() != null) {
                codigo = "" + aux.getCodigoBrigada().getCodBrigada() + "-" + aux.getCodigoBrigada().getNombreBrigada();
            }
            modelo2.addRow(new Object[]{aux.getCodigo(), aux.getFechaSiniestro(), aux.getTipoSiniestro(), codigo, aux.getDetalles()});
        }
    }

    public void armarTabla2() {

        modelo2.addColumn("Codigo");
        modelo2.addColumn("Fecha");
        modelo2.addColumn("Tipo");
        modelo2.addColumn("CodBrigada");
        modelo2.addColumn("Detalles");
        jTSiniestro.setModel(modelo2);
    }

    public void llenarCuartel() {
        jcCuartel.setModel(comboModelo);
        jcCuartelFiltro.setModel(comboModelo);
    }

    private void llenarTabla() {
        System.out.println("hola");
        modelo.setRowCount(0);
        brigadas=bData.listarBrigadas();
        for (Brigada aux : brigadas) {
            String nombre = "";
            for (Cuartel cuartel : listaCuartel) {
                if (cuartel.getCodCuartel() == aux.getNro_cuartel().getCodCuartel()) {
                    nombre = cuartel.getNombre();
                }
            }
            modelo.addRow(new Object[]{aux.getCodBrigada(), aux.getNombreBrigada(), aux.getEspecialidad(), nombre});
        }
    
        System.out.println("chau");
}}
